version: "3"

services:
  mariadb:
    container_name: kopling-restapi-boilerplate-mariadb
    image: mariadb:10
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql/:/var/lib/mysql
      - ./src/main/resources/sql/01.schema.sql:/docker-entrypoint-initdb.d/01.sql:rw
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_DATABASE: sample
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

networks:
  backend: